// <auto-generated />
using System;
using HamsterHub.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HamsterHub.Infrastructure.Migrations
{
    [DbContext(typeof(HamsterDbContext))]
    [Migration("20260421154405_RemoveImgFromHamster")]
    partial class RemoveImgFromHamster
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HamsterHub.Domain.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("HamsterId")
                        .HasColumnType("int");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HamsterId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("HamsterHub.Domain.Entities.Hamster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AgeInMonths")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Personality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PricePerDay")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("WeightInGrams")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Hamsters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgeInMonths = 8.0,
                            Description = "Världens mjukaste hamster.",
                            IsAvailable = true,
                            Name = "Mårten",
                            Personality = "Kelig",
                            PricePerDay = 99m,
                            WeightInGrams = 180
                        },
                        new
                        {
                            Id = 2,
                            AgeInMonths = 14.0,
                            Description = "Är det ens en hamster..?",
                            IsAvailable = true,
                            Name = "Kleffe",
                            Personality = "Lat",
                            PricePerDay = 75m,
                            WeightInGrams = 95
                        },
                        new
                        {
                            Id = 3,
                            AgeInMonths = 5.0,
                            Description = "Springer 12 km per natt.",
                            IsAvailable = true,
                            Name = "Blixten",
                            Personality = "Hyperaktiv",
                            PricePerDay = 89m,
                            WeightInGrams = 78
                        },
                        new
                        {
                            Id = 4,
                            AgeInMonths = 18.0,
                            Description = "Liten men farlig.",
                            IsAvailable = true,
                            Name = "Ragnar",
                            Personality = "Aggresiv",
                            PricePerDay = 49m,
                            WeightInGrams = 32
                        },
                        new
                        {
                            Id = 5,
                            AgeInMonths = 10.0,
                            Description = "Ingen vet vad hon tänker härnäst.",
                            IsAvailable = true,
                            Name = "Kajsa",
                            Personality = "Oförutsägbar",
                            PricePerDay = 120m,
                            WeightInGrams = 42
                        },
                        new
                        {
                            Id = 6,
                            AgeInMonths = 6.0,
                            Description = "Förälskar sig i alla hon möter. Även brevlådor.",
                            IsAvailable = true,
                            Name = "Valentina",
                            Personality = "Kärleksfull",
                            PricePerDay = 110m,
                            WeightInGrams = 120
                        },
                        new
                        {
                            Id = 7,
                            AgeInMonths = 9.0,
                            Description = "Har aldrig haft en dålig dag i hela sitt liv.",
                            IsAvailable = true,
                            Name = "Glenn",
                            Personality = "Glad",
                            PricePerDay = 95m,
                            WeightInGrams = 145
                        },
                        new
                        {
                            Id = 8,
                            AgeInMonths = 12.0,
                            Description = "Tar det lugnt. Extremt lugnt. Ibland för lugnt.",
                            IsAvailable = true,
                            Name = "Chilli",
                            Personality = "Chill",
                            PricePerDay = 80m,
                            WeightInGrams = 110
                        },
                        new
                        {
                            Id = 9,
                            AgeInMonths = 20.0,
                            Description = "Litar inte på någon. Inte ens dig. Speciellt inte dig.",
                            IsAvailable = true,
                            Name = "Skurt",
                            Personality = "Skeptisk",
                            PricePerDay = 85m,
                            WeightInGrams = 98
                        },
                        new
                        {
                            Id = 10,
                            AgeInMonths = 7.0,
                            Description = "Kramar allt som rör sig. Och en del som inte gör det.",
                            IsAvailable = true,
                            Name = "Doris",
                            Personality = "Kärleksfull",
                            PricePerDay = 105m,
                            WeightInGrams = 132
                        },
                        new
                        {
                            Id = 11,
                            AgeInMonths = 4.0,
                            Description = "Har inte suttit still en enda sekund sedan födseln.",
                            IsAvailable = true,
                            Name = "Turbo-Tobias",
                            Personality = "Hyperaktiv",
                            PricePerDay = 92m,
                            WeightInGrams = 67
                        },
                        new
                        {
                            Id = 12,
                            AgeInMonths = 22.0,
                            Description = "Har sett saker. Vill inte prata om det.",
                            IsAvailable = true,
                            Name = "Birgitta",
                            Personality = "Skeptisk",
                            PricePerDay = 78m,
                            WeightInGrams = 115
                        },
                        new
                        {
                            Id = 13,
                            AgeInMonths = 11.0,
                            Description = "Dyker upp precis där du minst anar det.",
                            IsAvailable = true,
                            Name = "Smygaren",
                            Personality = "Oförutsägbar",
                            PricePerDay = 115m,
                            WeightInGrams = 54
                        },
                        new
                        {
                            Id = 14,
                            AgeInMonths = 16.0,
                            Description = "Skrattar åt sina egna skämt. Skämten är faktiskt ganska bra.",
                            IsAvailable = true,
                            Name = "Roffe",
                            Personality = "Glad",
                            PricePerDay = 88m,
                            WeightInGrams = 158
                        },
                        new
                        {
                            Id = 15,
                            AgeInMonths = 24.0,
                            Description = "Liten. Arg. En Bitter jäkel.",
                            IsAvailable = true,
                            Name = "Magnusson",
                            Personality = "Aggresiv",
                            PricePerDay = 45m,
                            WeightInGrams = 28
                        },
                        new
                        {
                            Id = 16,
                            AgeInMonths = 13.0,
                            Description = "Gnäller hela dagen, varje dag...",
                            IsAvailable = true,
                            Name = "Zara",
                            Personality = "Aggresiv",
                            PricePerDay = 95m,
                            WeightInGrams = 103
                        },
                        new
                        {
                            Id = 17,
                            AgeInMonths = 19.0,
                            Description = "Nani gör absolut ingenting..",
                            IsAvailable = true,
                            Name = "Nani",
                            Personality = "Lat",
                            PricePerDay = 70m,
                            WeightInGrams = 188
                        },
                        new
                        {
                            Id = 18,
                            AgeInMonths = 6.0,
                            Description = "Vill bara ligga i knät. Helst ditt.",
                            IsAvailable = true,
                            Name = "Fröken Pippy",
                            Personality = "Kelig",
                            PricePerDay = 102m,
                            WeightInGrams = 91
                        },
                        new
                        {
                            Id = 19,
                            AgeInMonths = 9.0,
                            Description = "Ingen vet hur han tar sig ut ur buren. Inte ens han själv.",
                            IsAvailable = true,
                            Name = "Kaoz",
                            Personality = "Oförutsägbar",
                            PricePerDay = 130m,
                            WeightInGrams = 61
                        });
                });

            modelBuilder.Entity("HamsterHub.Domain.Entities.Booking", b =>
                {
                    b.HasOne("HamsterHub.Domain.Entities.Hamster", "Hamster")
                        .WithMany()
                        .HasForeignKey("HamsterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hamster");
                });
#pragma warning restore 612, 618
        }
    }
}
